name: reface
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40=hb3c18ed_4
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cuda-cudart=12.6.77=h5888daf_0
  - cuda-cudart_linux-64=12.6.77=h3f2d84a_0
  - cuda-nvrtc=12.6.85=hbd13f7d_0
  - cuda-version=12.6=h7480c83_3
  - cudnn=9.3.0.75=h93bb076_0
  - dlib=19.24.6=cuda120py310h6b6de5f_2
  - expat=2.7.1=h6a678d5_0
  - gcc_impl_linux-64=11.4.0=h00c12a0_13
  - gcc_linux-64=11.4.0=ha077dfb_4
  - gxx_impl_linux-64=11.4.0=h634f3ee_13
  - gxx_linux-64=11.4.0=h35bfe5d_4
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - krb5=1.21.3=h723845a_4
  - ld_impl_linux-64=2.40=h12ee557_0
  - libblas=3.9.0=35_h4a7cf45_openblas
  - libcblas=3.9.0=35_h0358290_openblas
  - libcublas=12.6.4.1=h5888daf_1
  - libcurand=10.3.7.77=hbd13f7d_0
  - libcurl=8.14.1=h332b0f4_0
  - libcusolver=11.7.1.2=h5888daf_1
  - libcusparse=12.5.4.2=hbd13f7d_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-devel_linux-64=11.4.0=h8f596e0_113
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgomp=15.1.0=h767d61c_5
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=35_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnvjitlink=12.9.86=h5888daf_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.50=h421ea60_1
  - libsanitizer=11.4.0=h5763a12_13
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-devel_linux-64=11.4.0=h8f596e0_113
  - libstdcxx-ng=15.1.0=h4852527_5
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hd590300_1
  - make=4.4.1=hb9d3cd8_2
  - nccl=2.27.7.1=h49b9d9a_3
  - ncurses=6.5=h7934f7d_0
  - ninja=1.13.1=h171cf75_0
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - python_abi=3.10=2_cp310
  - readline=8.3=hc2a1206_0
  - rhash=1.4.6=hb9d3cd8_1
  - sqlite=3.50.2=hb25bd0a_1
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - albumentations==1.1.0
      - altair==5.5.0
      - antlr4-python3-runtime==4.8
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - base58==2.1.1
      - bezier==2023.7.28
      - blinker==1.9.0
      - cachetools==6.2.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cmake==4.1.0
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.1.4
      - decorator==4.4.2
      - diffusers==0.30.3
      - dift==0.0.7
      - docker-pycreds==0.4.0
      - easydict==1.13
      - einops==0.4.1
      - face-alignment==1.4.1
      - filelock==3.19.1
      - flask==3.1.2
      - flatbuffers==25.9.23
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - ftfy==6.0.3
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.7.0
      - grpcio==1.74.0
      - hf-xet==1.1.10
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - imutils==0.5.4
      - insightface==0.7.3
      - invisible-watermark==0.2.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - kornia==0.6.0
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - markdown==3.9
      - markupsafe==3.0.2
      - matplotlib==3.10.7
      - ml-dtypes==0.5.3
      - more-itertools==10.5.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - multidict==6.6.4
      - narwhals==2.5.0
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==1.26.4
      - omegaconf==2.1.1
      - onnx==1.19.1
      - onnxruntime-gpu==1.16.3
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.12.0.88
      - packaging==24.1
      - pandas==2.0.3
      - pillow==11.3.0
      - platformdirs==4.4.0
      - prettytable==3.16.0
      - proglog==0.1.10
      - propcache==0.3.2
      - protobuf==5.29.5
      - psutil==7.0.0
      - pudb==2019.2
      - pydeck==0.9.1
      - pydeprecate==0.3.1
      - pygments==2.19.2
      - pyopengl==3.1.7
      - pyparsing==3.2.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.4.2
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - qudida==0.0.4
      - referencing==0.36.2
      - regex==2024.9.11
      - requests==2.32.3
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentry-sdk==2.37.1
      - setproctitle==1.3.7
      - setuptools==59.5.0
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==0.73.1
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - test-tube==0.7.5
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tokenizers==0.12.1
      - toml==0.10.2
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchmetrics==0.6.0
      - torchvision==0.14.1+cu117
      - tornado==6.5.2
      - tqdm==4.66.5
      - transformers==4.19.2
      - trimesh==4.4.9
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - tzlocal==5.3.1
      - urllib3==2.5.0
      - urwid==3.0.2
      - validators==0.35.0
      - wandb==0.18.1
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /home/shuangjun.du/anaconda3/envs/reface
